# Generated by Django 5.1.2 on 2024-10-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OM_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_description',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Phone', 'Phone'), ('Monitor', 'Monitor'), ('Mouse', 'Mouse'), ('Other', 'Other')], max_length=50),
        ),
    ]
