# Generated by Django 5.1.2 on 2024-10-22 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OM_app', '0005_alter_employeeasset_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeasset',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_employee', to='OM_app.asset'),
        ),
        migrations.AlterField(
            model_name='employeeasset',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assets', to='OM_app.employee'),
        ),
    ]
