# Generated by Django 5.1.2 on 2024-10-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OM_app', '0006_alter_employeeasset_asset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeasset',
            name='return_date',
        ),
        migrations.AddField(
            model_name='asset',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
