# Generated by Django 5.1.2 on 2024-10-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OM_app', '0008_remove_asset_return_date_employeeasset_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeasset',
            name='return_date',
        ),
    ]
